module.exports = {
  '@constructor': ['comment'],
  '@author': ['name'],
  '@deprecated': ['comment'],
  '@exception': ['type', 'comment'],
  '@param': ['type', 'name', 'comment'],
  '@private': ['comment'],
  '@return': ['type', 'comment'],
  '@returns': ['type', 'comment'],
  '@see': ['comment'],
  '@this': ['name', 'comment'],
  '@throws': ['type', 'comment'],
  '@version': ['version', 'comment'],
  '@method': ['name', 'comment'],
  '@override': ['comment'],
  '@const': ['comment'],
  '@type': ['type', 'comment'],
  '@extends': ['type', 'comment'],
  '@callback': ['namepath', 'comment'],
  '@reactive': ['comment'],
  '@where': ['where', 'comment'],
  '@copyright': ['copyrightText'],
};